name: third_iteration
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  flutter_advanced_drawer: ^1.3.2
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/illustrations/
    - assets/translations/
